#!/usr/bin/env bash

branches=$(git branch --merged | grep -v '^  develop' | grep -v '^\*' | awk '{print($1)}' | grep -v '^master$\|^develop$')

readarray -t branch_array <<<"$branches"

for b in $branch_array
do
git branch -D $b
done
