#!/usr/bin/env zsh

fetch(){
  curl $2 --silent -u $JIRA_USERNAME:$JIRA_TOKEN -X GET -H "Content-Type: application/json" "https://silkfred.atlassian.net/rest/api/2/$1"
}

result=$(fetch $1)


ruby_code=$(<<-EOF
a=gets
CONTROL_CHARACTERS = ("\x00".."\x1f").to_a.join("|")
REGEX= /#{CONTROL_CHARACTERS}/

lines = []

while a do
  lines << a.gsub(REGEX, "")

  a=gets
end

puts lines.join(" ")
EOF
)

selector=${2:-'.'}

echo $result | ruby -e $ruby_code | jq $selector 2> /dev/null || (echo $result && echo 'failed')
