#!/usr/bin/env zsh
# usage
# flow-jira <url_path> <jq selector>

fetch(){
  curl $2 --silent -u $JIRA_USERNAME:$JIRA_TOKEN -X PUT -H "Content-Type: application/json" "https://$JIRA_SUBDOMAIN.atlassian.net/$1"
}

url_path=$1
selector=${2:-'.'}

result=$(fetch $url_path)


ruby_code=$(<<-EOF
# JIRA responses include new lines and other control characters
# and jq doesn't like that

a=gets

CONTROL_CHARACTERS = ("\x00".."\x1f").to_a.join("|")
REGEX= /#{CONTROL_CHARACTERS}/

lines = []

while a do
  lines << a.gsub(REGEX, "")

  a=gets
end

puts lines.join(" ")
EOF
)

echo $result | ruby -e $ruby_code | jq $selector 2> /dev/null || (echo $result && echo 'failed')
